### ISSUE TITLE
TS0601 _TZE200_9yapgbuv Ef00 device

### ISSUE THREAD

**Issue by itzikta** [w35l3y/EdgeDrivers#3]
There is a problem with this module. Data cannot be seen
![inbound7694735347464115775](https://github.com/w35l3y/EdgeDrivers/assets/59511434/9f86a2f2-0601-4217-aaf3-42750178f153)
![inbound2284551528085315561](https://github.com/w35l3y/EdgeDrivers/assets/59511434/9f412550-4bec-4e75-9012-ac8ab0e4a68d)

**Comment by w35l3y** [comment]
Considering the datapoints shown, it seems to work similarly with [_TZE200_yjjdcqsq](https://github.com/w35l3y/EdgeDrivers/blob/ab5950635226c06060baaf3f50d1f61816d4397a/personal-tuya-devices/DEVICES.md?plain=1#L48)
It uses profile "normal-temphumibatt-v1"

To reach that profile, you would need to execute the following steps in the settings:
- Profile : Temperature & Humidity (normal-temphumi-v1)
- Profile : +Battery (normal-temphumibatt-v1)
- Manufacturer : _TZE200_yjjdcqsq

Also, considering you are using iPhone, you might need to close/open the app after each step explained above.
If these options doesn't show for you, wait a few seconds and try again. It is a known bug in the app.

**Comment by itzikta** [comment]
Hi, it doesn't work. You don't see data

בתאריך יום ד׳, 20 בספט׳ 2023, 14:08, מאת w35l3y ***@***.***>:

**Comment by itzikta** [comment]
Hi, it doesn't work. You don't see data
/
![Screenshot_20230920_150451_SmartThings](https://github.com/w35l3y/EdgeDrivers/assets/59511434/f34ff001-a943-464c-a1bc-85d28879ecee)

**Comment by w35l3y** [comment]
Have you closed the app after the last step ?

If so, use [logcat from smartthings-cli](https://github.com/SmartThingsCommunity/smartthings-cli#smartthings-edgedriverslogcat-driverid) filtered by this driver to extract some logs and share it here.

**Comment by w35l3y** [comment]
It is very common to see people reporting an error because they were using the wrong profile or because the app is reproducing one of the [known issues](https://github.com/w35l3y/EdgeDrivers/tree/beta/personal-tuya-devices#known-issues).

Issue closed due to inactivity.
