### ISSUE TITLE
Reporting Configuration

### ISSUE THREAD

**Issue by FreeMasen** [w35l3y/EdgeDrivers#6]
Hello, 

First off, thank you for this driver it is working quite well with my tuya human presence sensor! Looking at the logs though it seems that the device is reporting every second and I am wondering if it would be possible to adjust this to report less frequently?

**Comment by w35l3y** [comment]
> the device is reporting every second

I don't know any tuya device that respect reporting interval.

As you well pointed, the device reports its status and the driver can't do much about it.

Some devices have an option in the settings to change frequency, but I don't have any human presence sensor to help you with it.
